"""empty message

Revision ID: f35584bd6f81
Revises: 48b628984c54
Create Date: 2022-11-29 16:35:11.164891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35584bd6f81'
down_revision = '48b628984c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('user_token_password_key', type_='unique')
        batch_op.create_unique_constraint(None, ['token'])
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_token', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('user_token_password_key', ['password'])
        batch_op.drop_column('token')

    # ### end Alembic commands ###
