"""empty message

Revision ID: f9ef830195ff
Revises: ac756f8b2653
Create Date: 2022-11-26 05:49:33.308299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9ef830195ff'
down_revision = 'ac756f8b2653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_constraint('user_profile_id_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.create_foreign_key('user_profile_id_fkey', 'user', ['id'], ['id'])

    # ### end Alembic commands ###
